# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Pegah Shariati
title: Data Analyst
email: shariati.pegah@gmail.com
website: https://pegahshariati.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  pegahshariati
linkedin_username: pegah-shariati
# twitter_username: facespics
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  With over 5 years of experience, I act as a bridge between data teams and stakeholders.

  My proactive approach involves generating data-driven solutions to enhance reporting processes. Proficient in handling large-scale datasets from diverse sources like PostgreSQL and AWS, I utilize scripting languages like SQL, Python to analyze data, identify patterns, and mitigate project risks. I create intuitive, visually appealing dashboards using Tableau and Power BI.
  
  As a member of agile teams, I excel in managing multiple projects, adapting to evolving business requirements, and meeting deadlines.

  I am most skilled in: **Tableau**, **Power BI**, **Python** and **SQL**.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Tableau Visualizations
        link: https://public.tableau.com/app/profile/pegah.shariati
        # link_text: Project Website
        # additional_links:
        #   - title:  tableau_public
        #     icon: fab fa-tableau
        #     url: https://public.tableau.com/app/profile/pegah.shariati
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
          # This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          A collection of Tableau visualizations showcasing my data analysis and visualization skills. These projects demonstrate my ability to create interactive, insightful dashboards that communicate complex data effectively.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Walgreens
        link: https://www.walgreens.com
        # link_text: boringcompany.com
        sub_title: Data Analyst
        caption: March 2025 - Present
        description: |
          - Extract, clean and analyze Conversational AI pipeline data leveraging SQL and Python to monitor user-engagement metrics such as call traffics, virtual agent’s success rate, containment and application performance. Ensure end-to-end visibility and accuracy of pipelines by monitoring quality metrics and automated assessments post-deployment. Investigate and correct data anomalies through data ops and live dashboards. 
          - Develop and maintain automated data integration across different data sources to ensure consistent data availability. Connecting internal and external platforms such as third party analytical services, using REST API, and cloud storage solutions into centralized pipelines using python to enable real-time data ingestions. Design automation scripts to enhance efficient & error-free operational efficiency across analytical and reporting processes.
          - Design, build and maintain real-time interactive Power BI dashboards to communicate data-driven insights and speech science KPIs enabling executive teams and non-technical stakeholders. Partner with multidisciplinary teams including data science, engineering, product management to identify and fill data gaps, taking analytical initiatives and co-drive product strategy for deep business impact. 
      
      - layout: left
        title: Sunnova Energy
        link: www.sunnova.com
        # link_text: boringcompany.com
        sub_title: Data Analyst
        caption: October 2022 - October 2024
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Create, sustain, and publish 50+ interactive reports and dashboards to present actionable insights to executive-level audiences such as Revenue Management, HR, Accounting, Customer Insights, Sales, and Fleet Management. Use Tableau (Desktop, Online, Prep Builder, Server) to build automated, real-time dashboards, with expertise in predictive models, data visualization, interactive filters, custom calculations and KPI performance optimization.
          - Develop and manage data pipelines on CRM tools like Salesforce, utilizing PostgreSQL for data modeling, extraction, transformation and manipulation. Execute ETL processes using Python (Pandas) and Excel (PivotTables) ensuring efficient data structure management. Perform data warehouse management, monitoring tables and views to ensure performance, scalability, and efficient data retrieval. Collaborate with data science and engineer teams to address data needs in machine learning model deployments, supporting seamless integration and real-time data availability.
          - Document technical and business requirements through detailed project documentation aligned with Agile methodologies. Hold requirement gathering sessions with stakeholder and product managers, ensuring clarity and alignment on project goals across 7 different cross-functional teams. Use tools like Confluence and JIRA for work-flow management, sprint planning, backlog grooming, and tracking user stories. Develop user stories, acceptance criteria, and detailed documentation for future reference and continuous project improvement.
          - Conduct code reviews for Tableau projects and SQL queries, ensuring adherence to organizational standards and industry best practices. Review for accuracy, consistency, integrity of data usage and performance optimization while collaborating with developers to enhance data accuracy and report quality. Oversee production releases, utilizing unit testing, A/B testing, and Quality Assurance (QA) techniques to ensure smooth deployments.
      - layout: left
        title: University of Houston (MAHD Lab)
        link: https://uh.edu
        # link_text: boringcompany.com
        sub_title: Graduate Research Analyst
        caption: January 2019 - August 2022
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Collected user data using Twitter Python API, transformed into structured and analyzed user behavior to predict misinformation dissemination probabilities. Utilized Tableau for visualizations and content strategy optimization.
          - Designed and implemented a Web Scraping Pipeline for extracting structural data on county-level presidential votes. Utilized Python's Beautiful Soup library for HTML data extraction, parsing, and JSON creation, drastically improving data extraction efficiency and scalability for future tasks.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Houston
        caption: 2016 - 2018
        sub_title: M.A., Social Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in data analysis some of my other interests and hobbies are:
  #     - yellow news
  #     - professional cookie cooking

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
